remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Carl | Data Analyst
description: Transforming data into actionable insights through analysis, visualization, and strategic problem-solving\ncarlharievalencia@gmail.com
show_downloads: true
